Bageriet/Models/Bread.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Bageriet.Models
{
    public class Bread
    {
        //Automatic properties for the bread class

        public int BreadId { get; set; }
        public string Name { get; set; }
        public string ShortDescription { get; set; }
        public string LongDescription { get; set; }
        public decimal Price { get; set; }
        public string ImageUrl { get; set; }
        public bool InStock { get; set; }
        public int ProductId { get; set; }
        public Product Product { get; set; }
    }
}

Bageriet/ViewModels/BreadListViewModel.cs
using Bageriet.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Bageriet.ViewModels
{
    public class BreadListViewModel
    {
        public IEnumerable<Bread> Bread { get; set; }
        public IEnumerable<Product> Products { get; set; }
    }
}

Bageriet/Controllers/BreadController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Bageriet.Models;
using Bageriet.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

//Controller for the bread page
namespace Bageriet.Controllers
{
    public class BreadController : Controller
    {
        private readonly IBreadRepository _breadRepository;
        private readonly IProductRepository _productRepository;
        private readonly IRatingRepository _ratingRepository;


        public BreadController(IBreadRepository breadRepository, IProductRepository productRepository, IRatingRepository ratingRepository)
        {
            _breadRepository = breadRepository;
            _productRepository = productRepository;
            _ratingRepository = ratingRepository;
        }

        public ViewResult BreadList()
        {
            BreadListViewModel breadListViewModel = new BreadListViewModel
            {   
                //All bread and products are added to the breadListViewModel
                Bread = _breadRepository.AllBread,
                Products = _productRepository.AllProducts
            };

            //The created view is returned to the bread page (Bread.cshtml)
            return View(breadListViewModel);
        }

        public IActionResult BreadView(int id)
        {

            double avarage = 0;
            foreach (var rating in _ratingRepository.GetAllRatings(id))
            {
                avarage = avarage += rating.Grade;
            }
            double avarageGrade = avarage / _ratingRepository.GetAllRatings(id).Count();

            if (double.IsNaN(avarageGrade))
                avarageGrade = 0;


            BreadDetailsView breadDetailsView = new BreadDetailsView
            {
                Bread = _breadRepository.GetBreadById(id),
                Ratings = _ratingRepository.GetAllRatings(id),
                AvarageGrade = avarageGrade
            };
            return View(breadDetailsView);
        }
    }
}

Bageriet/Controllers/RatingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Bageriet.Models;
using Bageriet.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Bageriet.Controllers
{
    [Authorize]
    public class RatingController : Controller
    {
        private readonly IRatingRepository _ratingRepository;
        private readonly IBreadRepository _breadRepository;

        public RatingController(IRatingRepository ratingRepository, IBreadRepository breadRepository)
        {
            _ratingRepository = ratingRepository;
            _breadRepository = breadRepository;

        }

        // GET: /<controller>/
        public IActionResult RateBread(int id)
        {
            var bread = _breadRepository.GetBreadById(id);
            if (bread == null)
                return NotFound();

            ViewBag.BreadId = bread.BreadId;
            ViewBag.BreadImg = bread.ImageUrl;
            return View();
        }

        [HttpPost]
        public IActionResult RateBread(Rating rating, int id)
        {
            var bread = _breadRepository.GetBreadById(id);
            rating.Bread = bread;
            rating.BreadId = id;
            if (ModelState.IsValid)
            {
                _ratingRepository.CreateRating(rating);
                return RedirectToAction("RatingComplete");
            }
            ViewBag.BreadId = id;
            ViewBag.BreadImg = bread.ImageUrl;
            return View(rating);
        }

        public IActionResult RatingComplete()
        {
            ViewBag.CheckoutCompleteMessage = "Tack för ditt betyg!";
            return View();
        }
    }
}

Bageriet/Views/Bread/Bread.cshtml
@model BreadListViewModel
@{
    ViewData["Title"] = Model.Products.First().ProductName;
}

<h1 class="pt-3">@Model.Products.First().ProductName</h1>
<p class="pt-3">@Model.Products.First().Description</p>

<div class="pt-3 row flex-row ">
    @foreach (var bread in Model.Bread)
    {
    <div class="col-lg-3 col-sm-6 mb-4 col-xs-6">
        <div class="card" style="width: 16rem;">
            <img class="card-img-top" src="@bread.ImageUrl" alt="Card image cap">
            <div class="card-body">
                <h5 class="card-title">@bread.Name</h5>
                <p class="card-text">@bread.ShortDescription.</p>
                <h6>@bread.Price kr</h6>
            </div>
        </div>
    </div>
    }
</div>

Bageriet/Views/Bread/BreadList.cshtml
@model BreadListViewModel
@{
    ViewData["Title"] = Model.Products.First().ProductName;
}

<h1 class="pt-3">@Model.Products.First().ProductName</h1>
<hr />
<p class="pt-3">@Model.Products.First().Description</p>

<div class="pt-3 row flex-row ">
    @foreach (var bread in Model.Bread)
    {
    <div class="col-lg-3 col-sm-6 mb-4 col-xs-6">
        <div class="card" style="width: 16rem;">
            <img class="card-img-top" src="@bread.ImageUrl" alt="Card image cap">
            <div class="card-body">
                <h5>
                    <a style="color: #432711;"asp-controller="Bread" asp-action="BreadView" asp-route-id="@bread.BreadId">@bread.Name</a>
                </h5>
                <p class="card-text">@bread.ShortDescription.</p>
                <h6>@bread.Price kr</h6>
            </div>
        </div>
    </div>
    }
</div>

Bageriet/Views/Bread/BreadView.cshtml
@model BreadDetailsView

<div class="container">
    <div class="row pt-3">
        <div class="col-lg-5 pt-3">
            <h1>@Model.Bread.Name</h1>.
            <hr />
            <h5 class="pull-right">@Model.Bread.Price kr</h5>
            <h4>@Model.Bread.ShortDescription</h4>
            <p>@Model.Bread.LongDescription</p>

        </div>
        <div class="col-lg-4">
            <img class="img-responsive img-thumbnail" alt="@Model.Bread.Name" src="@Model.Bread.ImageUrl">
        </div>
        <div class="col-lg-3">
            <div>
                <hr />
                <h5>@Model.Bread.Name har fått:</h5>
                <p>@(Math.Round(Model.AvarageGrade, 1)) i medelbetyg (baserat på @Model.Ratings.Count() omdömen).</p>
                <hr />
                @foreach (var rating in Model.Ratings)
                {
                    <p><strong>@rating.AuthorName:</strong> @rating.Comment </p>
                    <h6>Betyg: @rating.Grade/5</h6>
                    <hr />
                }
                
                <a class="btn btn-secondary text-light" style="background:rgb(67,39,17) linear-gradient(0deg, rgba(67,39,17,1) 0%, rgba(51,41,41,1) 81%);" asp-controller="Rating" asp-action="RateBread" asp-route-Id="@Model.Bread.BreadId">Ge betyg</a>
            </div>
        </div>
        
    </div>
</div>